INSERT INTO crags (crag_name, region_id) 
VALUES ('Animal Crackers Wall',            1),
       ('The Arsenal',                     1),
       ('Bibliothek',                      1),
       ('The Boneyard',                    1),
       ('The Bowling Alley',               1),
       ('Bruisebrothers Wall',             1),
       ('Coyote Cliff',                    1),
       ('The Fire Wall',                   1),
       ('Great Arch',                      1),
       ('Great Wall',                      1),
       ('Guide Wall',                      1),
       ('The Hideout',                     1),
       ('Indy Wall',                       1),
       ('Inner Sanctum',                   1),
       ('Ivory Tower',                     1),
       ('Land Before Time Wall',           1),
       ('Midnight Surf',                   1),
       ('Persepolis',                      1),
       ('Practice Wall',                   1),
       ('The Sanctuary',                   1),
       ('Shawnee Shelter',                 1),
       ('Slab City',                       1),
       ('Solarium',                        1),
       ('South Side',                      1),
       ('The Stadium',                     1),
       ('The Stronghold',                  1),
       ('Sunbeam Buttress',                1),
       ('Sunnyside',                       1),
       ('Tectonic Wall and Johnny''s Wall',1),
       ('Washboard Wall',                  1);